# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 070d972bad4b5b54dd686fb184f05359c2ea49c80284d918c3ae7f20b39b5e2ce290afd2eb8cebd588872a1981c5830a88bdef682a305a1fb300a7e381013054

test:
  secret_key_base: 24bb6f3bd5907105cbf44bdc16a64ab7e9ca92e23975d1ef0a3cf46a1e3a40daddb7147823f452dff7e4f0021df5e4880346557bfd03d30dd232a3a88c28aecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
